[package]
name = "blog-assets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nipper = "0.1.*"
walkdir = "2"
regex = "*"
urlencoding = "*"